version: "3.9"

services:
  doctor_db:
    image: postgres:15-alpine
    container_name: doctor_appointment_db
    restart: always
    environment:
      POSTGRES_DB: doctor_appointment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - doctor_db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      target: backend
    container_name: doctor_appointment_backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: doctor_db
      DB_PORT: 5432        # internal container port
      DB_NAME: doctor_appointment_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: your-secret-key-change-in-production
      PORT: 5000
      NODE_ENV: production
      CLIENT_URL: http://localhost:3000
    depends_on:
      - doctor_db
    restart: unless-stopped

  frontend:
    build:
      context: .
      target: frontend
    container_name: doctor_appointment_frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:3000/api
      NEXT_PUBLIC_BACKEND_URL: http://localhost:5000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  doctor_db_data:
