version: "3.9"

services:
  doctor_db:
    image: postgres:15-alpine
    container_name: doctor_appointment_db
    restart: always
    environment:
      POSTGRES_DB: doctor_appointment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - doctor_db_data:/var/lib/postgresql/data

volumes:
  doctor_db_data:
